name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t username/repository-name:${{ github.sha }} .
        docker tag username/repository-name:${{ github.sha }} username/repository-name:latest

    # Step 4: Push the Docker image
    - name: Push Docker Image
      run: |
        docker push username/repository-name:${{ github.sha }}
        docker push username/repository-name:latest
